### ISSUE TITLE
Not working for .NET Docs repo

### ISSUE THREAD

**Issue by Thraka** [cillroy/dmc-toc-helper#1]
Our TOC uses these yml entries, which I can tell your tool does not look for (**tocHref topicHref**)

```
        - name: Events
          tocHref: /dotnet/visual-basic/programming-guide/language-features/events/
          topicHref: /dotnet/visual-basic/programming-guide/language-features/events/index
```

https://github.com/dotnet/docs/

**Comment by Thraka** [comment]
@cillroy

**Comment by cillroy** [comment]
Let me see about getting this added to https://github.com/cillroy/dmc-toc-helper

**Comment by cillroy** [comment]
I have updated the tool to support tocHref and topicHref now
